### ISSUE TITLE
remove old PII

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#218]
Hi,

We did discuss tools to remove old PII (for compliance with GDPR), is this done automatically? can it be run for a specific org only? with information about the cut-off date?

**Comment by marcinkoziej** [comment]
That was not implemented, and easy way to do so is to do this using SQL (also more control on what exactly is done).

The way to forget supporter data is to:

- update the `contacts` record for `(supporter_id, org_id)`
  - `set payload '{}', crypto_nonce = NULL, public_key_id = NULL, sign_key_id = NULL, updated_at = NOW()`
 
- update the `supporters` record for this supporter (they should be NULL because Proca nullifies these after thank you email but worth checking) - warning, supporters record is shared by orgs sharing this data.
  - `set first_name = NULL, email = NULL`

**Comment by tttp** [comment]
is this possible to delete them and update supporters to point to a "deleted placeholder" contact instead of nullifying it?

**Comment by marcinkoziej** [comment]
The supporters.fingerprint is still used to calculate signature counts so i would say replacing all deleted with a single placeholder record will reduce signature count to a deduplicated 1
